import {
  Building2,
  Camera,
  Compass,
  MapPinned,
  Video,
  type LucideIcon,
} from 'lucide-react-native';

/** Official CDRMS / Karnataka PWD field terminology — single source for UI copy. */
export const TERMS = {
  app: {
    shortName: 'CDRMS',
    fullName: 'Correct Dimension Report Management System',
    tagline: 'Correct Dimension Report Management',
    department: 'Government of India · Public Works',
    ministry: 'Ministry of Public Works',
    copyright: '© 2026 Ministry of Public Works',
    version: 'v 4.2.1',
  },
  roles: {
    fieldOfficer: 'Field Officer',
    assistantEngineer: 'Assistant Engineer',
    revenueOfficer: 'Revenue Officer',
    cao: 'CAO',
    caoOffice: 'Competent Authority Office',
    caoKarnataka: 'CAO Karnataka',
  },
  fields: {
    projectName: 'Work Name',
    khatedarName: 'Khatedar Name',
    surveyNo: 'Survey No.',
    plotNo: 'Plot No.',
    dimensionArea: 'Dimension / Area',
    roadType: 'Road Classification',
    landType: 'Land Classification',
    village: 'Village',
    hobli: 'Hobli',
    taluk: 'Taluk',
    district: 'District',
    state: 'State',
    gpsCoordinates: 'GPS Coordinates',
    administrativeArea: 'Administrative Jurisdiction',
    assignedSurvey: 'Assigned Survey',
    approachRoadWidth: 'Approach Road Width',
    approachRoadName: 'Approach Road Name',
    approachNotes: 'Approach / Access Notes',
    nearbyBuildings: 'Nearby Structures',
    nearbyRoads: 'Adjacent Roads',
    landmarks: 'Landmarks / Reference Points',
    employeeId: 'Employee ID',
    mobileNumber: 'Mobile Number',
  },
  sections: {
    siteParticulars: 'Site Particulars',
    administrativeArea: 'Administrative Jurisdiction',
    projectWorkspace: 'Dimension Report Workspace',
    siteLocation: 'Site Location (Geo-tag)',
    siteMatchDetails: 'Survey Site Verification',
    locationCheck: 'On-site Location Check',
    boundaryCompass: 'Boundary Compass',
    boundaryDirections: 'Boundary Directions',
    directionalPhotos: 'Directional Photographs',
    nearbyContext: 'Adjacent Site Context',
    sitePhotoGallery: 'Site Photograph Gallery',
    walkthroughVideo: 'Site Inspection Video',
    media: 'Photographs & Video',
    approachDetails: 'Approach Road Particulars',
    directions: 'Boundary Directions',
    surroundings: 'Site Surroundings',
    checklist: 'Pre-submission Checklist',
    caoRemarks: 'CAO Remarks',
  },
  workflow: {
    newApplication: 'New Dimension Report',
    newApplicationSubtitle: 'Capture site particulars for CAO verification.',
    fixResubmit: 'Fix & Resubmit',
    fixResubmitSubtitle: 'Update returned fields, then continue through validation.',
    checkBandi: 'Check Bandi',
    checkBandiSubtitle: 'Confirm on-site presence and record boundary directions.',
    checkBandiRemarksSubtitle: 'Record field observations or Bandi remarks',
    checkBandiPlaceholder:
      'e.g. Boundary pillar missing on north side, encroachment noted…',
    directionsSubtitle: 'Record boundary particulars for each cardinal direction.',
    surroundingsSubtitle: 'Capture directional photographs of the site environment.',
    photosSubtitle: 'Upload clear geo-tagged site photographs — max 10 images.',
    videoSubtitle: 'Record a short site inspection walk-through video.',
    validate: 'Validate Report',
    validateSubtitle: 'Pre-submission checklist before CAO review.',
    reviewSubmit: 'Review & Submit',
    reviewSubmitSubtitle: 'Verify all particulars before submission to CAO.',
    continueToCheckBandi: 'Continue to Check Bandi',
    continueToDirections: 'Continue to Boundary Directions',
    continueToSurroundings: 'Continue to Site Surroundings',
    continueToPhotos: 'Continue to Photographs',
    continueToVideo: 'Continue to Video',
    validateApplication: 'Validate Dimension Report',
    physicalVerification:
      'I have physically verified this\nlocation on site (Bandi checked).',
    fixCaoRemarks: 'Address CAO remarks',
    returnedByCao: 'Returned by Competent Authority Office',
  },
  validation: {
    projectDetails: 'Site Particulars',
    gpsCoordinates: 'GPS Coordinates',
    checkBandi: 'Check Bandi Verification',
    directionsBoundaries: 'Boundary Directions',
    surroundingPhotos: 'Directional Photographs',
    sitePhotos: 'Site Photographs',
    walkthroughVideo: 'Site Inspection Video',
  },
  status: {
    draft: 'Draft',
    submitted: 'Submitted',
    returned: 'Returned',
    verified: 'Verified',
    rejected: 'Rejected',
  },
  permissions: {
    gpsTitle: 'Precise Location (GPS)',
    foregroundTitle: 'Location While Using App',
    foregroundDesc: 'Enables Check Bandi verification & geo-fence',
    backgroundTitle: 'Background Location',
    geoValidation: 'Geo Validation',
    geoValidationSubtitle: 'Verifying assigned jurisdiction',
  },
  dashboard: {
    createApplication: 'Create Dimension Report',
    createApplicationDesc: 'Start new report',
    continueDraft: 'Continue Draft',
    startSurvey: 'Resume Field Survey',
    startSurveyDesc: 'Check Bandi & boundary directions',
    viewHistory: 'View History',
    viewHistoryDesc: 'All dimension reports',
  },
} as const;

export type SurveyStep = {
  label: string;
  short: string;
  title: string;
  icon: LucideIcon;
};

/** Five-step field survey workflow — Bandi + boundary directions share one step. */
export const SURVEY_STEPS: SurveyStep[] = [
  {
    label: 'Site Details',
    short: 'Site',
    title: TERMS.sections.siteParticulars,
    icon: Building2,
  },
  {
    label: TERMS.workflow.checkBandi,
    short: 'Bandi',
    title: TERMS.workflow.checkBandi,
    icon: MapPinned,
  },
  {
    label: 'Surroundings',
    short: 'Surrounds',
    title: TERMS.sections.surroundings,
    icon: Compass,
  },
  {
    label: 'Photographs',
    short: 'Photos',
    title: TERMS.sections.sitePhotoGallery,
    icon: Camera,
  },
  {
    label: 'Video',
    short: 'Video',
    title: TERMS.sections.walkthroughVideo,
    icon: Video,
  },
];
